/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import type { Mesh } from 'three'
import type { MeshVisibility, MaterialMode } from './mesh-visibility-panel'
import { DeviationMaterial } from '@/components/deviation-material'
import { RGBMaterial } from '@/components/rgb-material'

interface RamlabMeshesProps {
  visibility?: MeshVisibility
  materialMode?: MaterialMode
  [key: string]: any
}

export function RamlabMeshes({ visibility, materialMode = 'gray', ...props }: RamlabMeshesProps) {
  const { nodes } = useGLTF('/meshes/ramlab_draco_prefix_meshattr.glb')
  
  // Default to all visible if no visibility prop provided
  const showTarget = visibility?.targetMesh ?? true
  const showResult = visibility?.resultMesh ?? true

  // Get the result mesh geometry
  const resultGeometry = (nodes.result_mesh as Mesh).geometry

  return (
    <group {...props} dispose={null} rotation={[0, Math.PI, 0]}>
      {showTarget && (
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.target_mesh as Mesh).geometry}
          material={(nodes.target_mesh as Mesh).material}
          scale={0.01}
        />
      )}
      {showResult && (
        <mesh
          castShadow
          receiveShadow
          geometry={resultGeometry}
          scale={0.01}
        >
          {materialMode === 'gray' && (
            <meshStandardMaterial 
              color="#888888"
              metalness={0.1}
              roughness={0.8}
            />
          )}
          {materialMode === 'rgb' && (
            <RGBMaterial />
          )}
          {materialMode === 'deviation' && (
            <DeviationMaterial />
          )}
        </mesh>
      )}
    </group>
  )
}

useGLTF.preload('/meshes/ramlab_draco_prefix_meshattr.glb')
