/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import type { Mesh } from 'three'
import type { MeshVisibility } from './mesh-visibility-panel'

interface RamlabMeshesProps {
  visibility?: MeshVisibility
  [key: string]: any
}

export function RamlabMeshes({ visibility, ...props }: RamlabMeshesProps) {
  const { nodes, materials } = useGLTF('/meshes/result_mesh_compressed.glb')
  
  // Default to all visible if no visibility prop provided
  const showTarget = visibility?.targetMesh ?? true
  const showResult = visibility?.resultMesh ?? true

  return (
    <group {...props} dispose={null} rotation={[0, Math.PI, 0]}>
      {showTarget && (
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.target_mesh as Mesh).geometry}
          material={(nodes.target_mesh as Mesh).material}
          scale={0.01}
        />
      )}
      {showResult && (
        <mesh
          castShadow
          receiveShadow
          geometry={(nodes.result_mesh as Mesh).geometry}
          material={materials.Deviation}
          scale={0.01}
        />
      )}
    </group>
  )
}

useGLTF.preload('/meshes/result_mesh_compressed.glb')
